name: notify
on:
  schedule:
    - cron: '0/5 * * * *'
  push:
    branches:
      - 'test/notify'
jobs:
  ci:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yarn
        run: npm i -g yarn
      - name: notify
        run: yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
