name: notify
on:
  schedule:
    - cron: '* */2 * * *'
  push:
    branches:
      - main
      - 'test/notify'
jobs:
  ci:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yarn
        run: npm i -g yarn
      - name: notify
        run: yarn start
        env:
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
